# FreeMusicApi2 SDK configuration

module FreeMusicApi2Config
  def self.make_config
    {
      "main" => {
        "name" => "FreeMusicApi2",
      },
      "feature" => {
        "test" => {
          "options" => {
            "active" => false,
          },
        },
      },
      "options" => {
        "base" => "https://www.theaudiodb.com/api/v1/json/123",
        "auth" => {
          "prefix" => "Bearer",
        },
        "headers" => {
          "content-type" => "application/json",
        },
        "entity" => {
          "v1_list" => {},
          "v1_lookup" => {},
          "v1_search" => {},
          "v2_list" => {},
          "v2_lookup" => {},
          "v2_search" => {},
        },
      },
      "entity" => {
        "v1_list" => {
          "fields" => [
            {
              "active" => true,
              "name" => "id_album",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 0,
            },
            {
              "active" => true,
              "name" => "id_artist",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 1,
            },
            {
              "active" => true,
              "name" => "id_imvdb",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 2,
            },
            {
              "active" => true,
              "name" => "id_lyric",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 3,
            },
            {
              "active" => true,
              "name" => "id_track",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 4,
            },
            {
              "active" => true,
              "name" => "int_cd",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 5,
            },
            {
              "active" => true,
              "name" => "int_duration",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 6,
            },
            {
              "active" => true,
              "name" => "int_loved",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 7,
            },
            {
              "active" => true,
              "name" => "int_music_vid_comment",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 8,
            },
            {
              "active" => true,
              "name" => "int_music_vid_dislike",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 9,
            },
            {
              "active" => true,
              "name" => "int_music_vid_favorite",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 10,
            },
            {
              "active" => true,
              "name" => "int_music_vid_like",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 11,
            },
            {
              "active" => true,
              "name" => "int_music_vid_view",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 12,
            },
            {
              "active" => true,
              "name" => "int_score",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 13,
            },
            {
              "active" => true,
              "name" => "int_score_vote",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 14,
            },
            {
              "active" => true,
              "name" => "int_total_listener",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 15,
            },
            {
              "active" => true,
              "name" => "int_total_play",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 16,
            },
            {
              "active" => true,
              "name" => "int_track_number",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 17,
            },
            {
              "active" => true,
              "name" => "loved",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 18,
            },
            {
              "active" => true,
              "name" => "str_album",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 19,
            },
            {
              "active" => true,
              "name" => "str_artist",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 20,
            },
            {
              "active" => true,
              "name" => "str_artist_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 21,
            },
            {
              "active" => true,
              "name" => "str_description_en",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 22,
            },
            {
              "active" => true,
              "name" => "str_genre",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 23,
            },
            {
              "active" => true,
              "name" => "str_locked",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 24,
            },
            {
              "active" => true,
              "name" => "str_mood",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 25,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_album_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 26,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_artist_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 27,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 28,
            },
            {
              "active" => true,
              "name" => "str_music_vid",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 29,
            },
            {
              "active" => true,
              "name" => "str_music_vid_company",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 30,
            },
            {
              "active" => true,
              "name" => "str_music_vid_director",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 31,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen1",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 32,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen2",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 33,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen3",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 34,
            },
            {
              "active" => true,
              "name" => "str_style",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 35,
            },
            {
              "active" => true,
              "name" => "str_theme",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 36,
            },
            {
              "active" => true,
              "name" => "str_track",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 37,
            },
            {
              "active" => true,
              "name" => "str_track_lyric",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 38,
            },
            {
              "active" => true,
              "name" => "str_track_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 39,
            },
            {
              "active" => true,
              "name" => "trending",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 40,
            },
          ],
          "name" => "v1_list",
          "op" => {
            "list" => {
              "input" => "data",
              "name" => "list",
              "points" => [
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "us",
                        "kind" => "query",
                        "name" => "country",
                        "orig" => "country",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                      {
                        "active" => true,
                        "example" => "albums",
                        "kind" => "query",
                        "name" => "format",
                        "orig" => "format",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                      {
                        "active" => true,
                        "example" => "itunes",
                        "kind" => "query",
                        "name" => "type",
                        "orig" => "type",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/trending.php",
                  "parts" => [
                    "trending.php",
                  ],
                  "select" => {
                    "exist" => [
                      "country",
                      "format",
                      "type",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 0,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "track",
                        "kind" => "query",
                        "name" => "format",
                        "orig" => "format",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/mostloved.php",
                  "parts" => [
                    "mostloved.php",
                  ],
                  "select" => {
                    "exist" => [
                      "format",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 1,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "cc197bad-dc9c-440d-a5b5-d52ba2e14234",
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/mvid-mb.php",
                  "parts" => [
                    "mvid-mb.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 2,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => 112024,
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/mvid.php",
                  "parts" => [
                    "mvid.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 3,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "cc197bad-dc9c-440d-a5b5-d52ba2e14234",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/track-top10-mb.php",
                  "parts" => [
                    "track-top10-mb.php",
                  ],
                  "select" => {
                    "exist" => [
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 4,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "coldplay",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/track-top10.php",
                  "parts" => [
                    "track-top10.php",
                  ],
                  "select" => {
                    "exist" => [
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 5,
                },
              ],
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "v1_lookup" => {
          "fields" => [
            {
              "active" => true,
              "name" => "id_album",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 0,
            },
            {
              "active" => true,
              "name" => "id_artist",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 1,
            },
            {
              "active" => true,
              "name" => "id_imvdb",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 2,
            },
            {
              "active" => true,
              "name" => "id_label",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 3,
            },
            {
              "active" => true,
              "name" => "id_lyric",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 4,
            },
            {
              "active" => true,
              "name" => "id_track",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 5,
            },
            {
              "active" => true,
              "name" => "int_born_year",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 6,
            },
            {
              "active" => true,
              "name" => "int_cd",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 7,
            },
            {
              "active" => true,
              "name" => "int_charted",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 8,
            },
            {
              "active" => true,
              "name" => "int_died_year",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 9,
            },
            {
              "active" => true,
              "name" => "int_duration",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 10,
            },
            {
              "active" => true,
              "name" => "int_formed_year",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 11,
            },
            {
              "active" => true,
              "name" => "int_loved",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 12,
            },
            {
              "active" => true,
              "name" => "int_member",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 13,
            },
            {
              "active" => true,
              "name" => "int_music_vid_comment",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 14,
            },
            {
              "active" => true,
              "name" => "int_music_vid_dislike",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 15,
            },
            {
              "active" => true,
              "name" => "int_music_vid_favorite",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 16,
            },
            {
              "active" => true,
              "name" => "int_music_vid_like",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 17,
            },
            {
              "active" => true,
              "name" => "int_music_vid_view",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 18,
            },
            {
              "active" => true,
              "name" => "int_sale",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 19,
            },
            {
              "active" => true,
              "name" => "int_score",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 20,
            },
            {
              "active" => true,
              "name" => "int_score_vote",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 21,
            },
            {
              "active" => true,
              "name" => "int_total_listener",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 22,
            },
            {
              "active" => true,
              "name" => "int_total_play",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 23,
            },
            {
              "active" => true,
              "name" => "int_track_number",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 24,
            },
            {
              "active" => true,
              "name" => "int_year_released",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 25,
            },
            {
              "active" => true,
              "name" => "str_album",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 26,
            },
            {
              "active" => true,
              "name" => "str_album3_d_case",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 27,
            },
            {
              "active" => true,
              "name" => "str_album3_d_face",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 28,
            },
            {
              "active" => true,
              "name" => "str_album3_d_flat",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 29,
            },
            {
              "active" => true,
              "name" => "str_album3_d_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 30,
            },
            {
              "active" => true,
              "name" => "str_album_c_dart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 31,
            },
            {
              "active" => true,
              "name" => "str_album_spine",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 32,
            },
            {
              "active" => true,
              "name" => "str_album_stripped",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 33,
            },
            {
              "active" => true,
              "name" => "str_album_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 34,
            },
            {
              "active" => true,
              "name" => "str_album_thumb_back",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 35,
            },
            {
              "active" => true,
              "name" => "str_album_thumb_hq",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 36,
            },
            {
              "active" => true,
              "name" => "str_all_music_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 37,
            },
            {
              "active" => true,
              "name" => "str_amazon_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 38,
            },
            {
              "active" => true,
              "name" => "str_apple_music",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 39,
            },
            {
              "active" => true,
              "name" => "str_artist",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 40,
            },
            {
              "active" => true,
              "name" => "str_artist_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 41,
            },
            {
              "active" => true,
              "name" => "str_artist_banner",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 42,
            },
            {
              "active" => true,
              "name" => "str_artist_clearart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 43,
            },
            {
              "active" => true,
              "name" => "str_artist_cutout",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 44,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 45,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart2",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 46,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart3",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 47,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart4",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 48,
            },
            {
              "active" => true,
              "name" => "str_artist_logo",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 49,
            },
            {
              "active" => true,
              "name" => "str_artist_stripped",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 50,
            },
            {
              "active" => true,
              "name" => "str_artist_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 51,
            },
            {
              "active" => true,
              "name" => "str_artist_wide_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 52,
            },
            {
              "active" => true,
              "name" => "str_bbc_review_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 53,
            },
            {
              "active" => true,
              "name" => "str_biography_cn",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 54,
            },
            {
              "active" => true,
              "name" => "str_biography_de",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 55,
            },
            {
              "active" => true,
              "name" => "str_biography_e",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 56,
            },
            {
              "active" => true,
              "name" => "str_biography_en",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 57,
            },
            {
              "active" => true,
              "name" => "str_biography_fr",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 58,
            },
            {
              "active" => true,
              "name" => "str_biography_hu",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 59,
            },
            {
              "active" => true,
              "name" => "str_biography_il",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 60,
            },
            {
              "active" => true,
              "name" => "str_biography_it",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 61,
            },
            {
              "active" => true,
              "name" => "str_biography_jp",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 62,
            },
            {
              "active" => true,
              "name" => "str_biography_nl",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 63,
            },
            {
              "active" => true,
              "name" => "str_biography_no",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 64,
            },
            {
              "active" => true,
              "name" => "str_biography_pl",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 65,
            },
            {
              "active" => true,
              "name" => "str_biography_pt",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 66,
            },
            {
              "active" => true,
              "name" => "str_biography_ru",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 67,
            },
            {
              "active" => true,
              "name" => "str_biography_se",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 68,
            },
            {
              "active" => true,
              "name" => "str_country",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 69,
            },
            {
              "active" => true,
              "name" => "str_country_code",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 70,
            },
            {
              "active" => true,
              "name" => "str_description_en",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 71,
            },
            {
              "active" => true,
              "name" => "str_disbanded",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 72,
            },
            {
              "active" => true,
              "name" => "str_discogs_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 73,
            },
            {
              "active" => true,
              "name" => "str_facebook",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 74,
            },
            {
              "active" => true,
              "name" => "str_gender",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 75,
            },
            {
              "active" => true,
              "name" => "str_genius_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 76,
            },
            {
              "active" => true,
              "name" => "str_genre",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 77,
            },
            {
              "active" => true,
              "name" => "str_instagram",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 78,
            },
            {
              "active" => true,
              "name" => "str_itunes_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 79,
            },
            {
              "active" => true,
              "name" => "str_label",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 80,
            },
            {
              "active" => true,
              "name" => "str_last_fm_chart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 81,
            },
            {
              "active" => true,
              "name" => "str_location",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 82,
            },
            {
              "active" => true,
              "name" => "str_locked",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 83,
            },
            {
              "active" => true,
              "name" => "str_lyric_wiki_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 84,
            },
            {
              "active" => true,
              "name" => "str_mood",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 85,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_album_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 86,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_artist_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 87,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 88,
            },
            {
              "active" => true,
              "name" => "str_music_moz_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 89,
            },
            {
              "active" => true,
              "name" => "str_music_vid",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 90,
            },
            {
              "active" => true,
              "name" => "str_music_vid_company",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 91,
            },
            {
              "active" => true,
              "name" => "str_music_vid_director",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 92,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen1",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 93,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen2",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 94,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen3",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 95,
            },
            {
              "active" => true,
              "name" => "str_rate_your_music_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 96,
            },
            {
              "active" => true,
              "name" => "str_release_format",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 97,
            },
            {
              "active" => true,
              "name" => "str_review",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 98,
            },
            {
              "active" => true,
              "name" => "str_sound_cloud",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 99,
            },
            {
              "active" => true,
              "name" => "str_speed",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 100,
            },
            {
              "active" => true,
              "name" => "str_spotify",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 101,
            },
            {
              "active" => true,
              "name" => "str_style",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 102,
            },
            {
              "active" => true,
              "name" => "str_theme",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 103,
            },
            {
              "active" => true,
              "name" => "str_track",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 104,
            },
            {
              "active" => true,
              "name" => "str_track_lyric",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 105,
            },
            {
              "active" => true,
              "name" => "str_track_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 106,
            },
            {
              "active" => true,
              "name" => "str_twitter",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 107,
            },
            {
              "active" => true,
              "name" => "str_website",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 108,
            },
            {
              "active" => true,
              "name" => "str_wikidata_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 109,
            },
            {
              "active" => true,
              "name" => "str_wikipedia_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 110,
            },
            {
              "active" => true,
              "name" => "str_youtube",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 111,
            },
          ],
          "name" => "v1_lookup",
          "op" => {
            "list" => {
              "input" => "data",
              "name" => "list",
              "points" => [
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => 32793500,
                        "kind" => "query",
                        "name" => "h",
                        "orig" => "h",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                      },
                      {
                        "active" => true,
                        "example" => 2115888,
                        "kind" => "query",
                        "name" => "m",
                        "orig" => "m",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/track.php",
                  "parts" => [
                    "track.php",
                  ],
                  "select" => {
                    "exist" => [
                      "h",
                      "m",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 0,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => 112024,
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                      },
                      {
                        "active" => true,
                        "example" => 2115888,
                        "kind" => "query",
                        "name" => "m",
                        "orig" => "m",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/album.php",
                  "parts" => [
                    "album.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                      "m",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 1,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "1dc4c347-a1db-32aa-b14f-bc9cc507b843",
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/album-mb.php",
                  "parts" => [
                    "album-mb.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 2,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "cc197bad-dc9c-440d-a5b5-d52ba2e14234",
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/artist-mb.php",
                  "parts" => [
                    "artist-mb.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 3,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => 112024,
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/artist-social.php",
                  "parts" => [
                    "artist-social.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 4,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => 112024,
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/artist.php",
                  "parts" => [
                    "artist.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 5,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "50369905-68ca-48d2-912d-b37330ff7dc3",
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/track-mb.php",
                  "parts" => [
                    "track-mb.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 6,
                },
              ],
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "v1_search" => {
          "fields" => [
            {
              "active" => true,
              "name" => "id_album",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 0,
            },
            {
              "active" => true,
              "name" => "id_artist",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 1,
            },
            {
              "active" => true,
              "name" => "id_imvdb",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 2,
            },
            {
              "active" => true,
              "name" => "id_label",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 3,
            },
            {
              "active" => true,
              "name" => "id_lyric",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 4,
            },
            {
              "active" => true,
              "name" => "id_track",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 5,
            },
            {
              "active" => true,
              "name" => "int_born_year",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 6,
            },
            {
              "active" => true,
              "name" => "int_cd",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 7,
            },
            {
              "active" => true,
              "name" => "int_charted",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 8,
            },
            {
              "active" => true,
              "name" => "int_died_year",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 9,
            },
            {
              "active" => true,
              "name" => "int_duration",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 10,
            },
            {
              "active" => true,
              "name" => "int_formed_year",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 11,
            },
            {
              "active" => true,
              "name" => "int_loved",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 12,
            },
            {
              "active" => true,
              "name" => "int_member",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 13,
            },
            {
              "active" => true,
              "name" => "int_music_vid_comment",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 14,
            },
            {
              "active" => true,
              "name" => "int_music_vid_dislike",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 15,
            },
            {
              "active" => true,
              "name" => "int_music_vid_favorite",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 16,
            },
            {
              "active" => true,
              "name" => "int_music_vid_like",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 17,
            },
            {
              "active" => true,
              "name" => "int_music_vid_view",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 18,
            },
            {
              "active" => true,
              "name" => "int_sale",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 19,
            },
            {
              "active" => true,
              "name" => "int_score",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 20,
            },
            {
              "active" => true,
              "name" => "int_score_vote",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 21,
            },
            {
              "active" => true,
              "name" => "int_total_listener",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 22,
            },
            {
              "active" => true,
              "name" => "int_total_play",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 23,
            },
            {
              "active" => true,
              "name" => "int_track_number",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 24,
            },
            {
              "active" => true,
              "name" => "int_year_released",
              "req" => false,
              "type" => "`$INTEGER`",
              "index$" => 25,
            },
            {
              "active" => true,
              "name" => "str_album",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 26,
            },
            {
              "active" => true,
              "name" => "str_album3_d_case",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 27,
            },
            {
              "active" => true,
              "name" => "str_album3_d_face",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 28,
            },
            {
              "active" => true,
              "name" => "str_album3_d_flat",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 29,
            },
            {
              "active" => true,
              "name" => "str_album3_d_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 30,
            },
            {
              "active" => true,
              "name" => "str_album_c_dart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 31,
            },
            {
              "active" => true,
              "name" => "str_album_spine",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 32,
            },
            {
              "active" => true,
              "name" => "str_album_stripped",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 33,
            },
            {
              "active" => true,
              "name" => "str_album_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 34,
            },
            {
              "active" => true,
              "name" => "str_album_thumb_back",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 35,
            },
            {
              "active" => true,
              "name" => "str_album_thumb_hq",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 36,
            },
            {
              "active" => true,
              "name" => "str_all_music_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 37,
            },
            {
              "active" => true,
              "name" => "str_amazon_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 38,
            },
            {
              "active" => true,
              "name" => "str_artist",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 39,
            },
            {
              "active" => true,
              "name" => "str_artist_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 40,
            },
            {
              "active" => true,
              "name" => "str_artist_banner",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 41,
            },
            {
              "active" => true,
              "name" => "str_artist_clearart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 42,
            },
            {
              "active" => true,
              "name" => "str_artist_cutout",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 43,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 44,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart2",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 45,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart3",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 46,
            },
            {
              "active" => true,
              "name" => "str_artist_fanart4",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 47,
            },
            {
              "active" => true,
              "name" => "str_artist_logo",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 48,
            },
            {
              "active" => true,
              "name" => "str_artist_stripped",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 49,
            },
            {
              "active" => true,
              "name" => "str_artist_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 50,
            },
            {
              "active" => true,
              "name" => "str_artist_wide_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 51,
            },
            {
              "active" => true,
              "name" => "str_bbc_review_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 52,
            },
            {
              "active" => true,
              "name" => "str_biography_cn",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 53,
            },
            {
              "active" => true,
              "name" => "str_biography_de",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 54,
            },
            {
              "active" => true,
              "name" => "str_biography_e",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 55,
            },
            {
              "active" => true,
              "name" => "str_biography_en",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 56,
            },
            {
              "active" => true,
              "name" => "str_biography_fr",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 57,
            },
            {
              "active" => true,
              "name" => "str_biography_hu",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 58,
            },
            {
              "active" => true,
              "name" => "str_biography_il",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 59,
            },
            {
              "active" => true,
              "name" => "str_biography_it",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 60,
            },
            {
              "active" => true,
              "name" => "str_biography_jp",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 61,
            },
            {
              "active" => true,
              "name" => "str_biography_nl",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 62,
            },
            {
              "active" => true,
              "name" => "str_biography_no",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 63,
            },
            {
              "active" => true,
              "name" => "str_biography_pl",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 64,
            },
            {
              "active" => true,
              "name" => "str_biography_pt",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 65,
            },
            {
              "active" => true,
              "name" => "str_biography_ru",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 66,
            },
            {
              "active" => true,
              "name" => "str_biography_se",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 67,
            },
            {
              "active" => true,
              "name" => "str_country",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 68,
            },
            {
              "active" => true,
              "name" => "str_country_code",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 69,
            },
            {
              "active" => true,
              "name" => "str_description_en",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 70,
            },
            {
              "active" => true,
              "name" => "str_disbanded",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 71,
            },
            {
              "active" => true,
              "name" => "str_discogs_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 72,
            },
            {
              "active" => true,
              "name" => "str_facebook",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 73,
            },
            {
              "active" => true,
              "name" => "str_gender",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 74,
            },
            {
              "active" => true,
              "name" => "str_genius_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 75,
            },
            {
              "active" => true,
              "name" => "str_genre",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 76,
            },
            {
              "active" => true,
              "name" => "str_itunes_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 77,
            },
            {
              "active" => true,
              "name" => "str_label",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 78,
            },
            {
              "active" => true,
              "name" => "str_last_fm_chart",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 79,
            },
            {
              "active" => true,
              "name" => "str_location",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 80,
            },
            {
              "active" => true,
              "name" => "str_locked",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 81,
            },
            {
              "active" => true,
              "name" => "str_lyric_wiki_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 82,
            },
            {
              "active" => true,
              "name" => "str_mood",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 83,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_album_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 84,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_artist_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 85,
            },
            {
              "active" => true,
              "name" => "str_music_brainz_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 86,
            },
            {
              "active" => true,
              "name" => "str_music_moz_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 87,
            },
            {
              "active" => true,
              "name" => "str_music_vid",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 88,
            },
            {
              "active" => true,
              "name" => "str_music_vid_company",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 89,
            },
            {
              "active" => true,
              "name" => "str_music_vid_director",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 90,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen1",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 91,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen2",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 92,
            },
            {
              "active" => true,
              "name" => "str_music_vid_screen3",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 93,
            },
            {
              "active" => true,
              "name" => "str_rate_your_music_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 94,
            },
            {
              "active" => true,
              "name" => "str_release_format",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 95,
            },
            {
              "active" => true,
              "name" => "str_review",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 96,
            },
            {
              "active" => true,
              "name" => "str_speed",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 97,
            },
            {
              "active" => true,
              "name" => "str_style",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 98,
            },
            {
              "active" => true,
              "name" => "str_theme",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 99,
            },
            {
              "active" => true,
              "name" => "str_track",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 100,
            },
            {
              "active" => true,
              "name" => "str_track_lyric",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 101,
            },
            {
              "active" => true,
              "name" => "str_track_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 102,
            },
            {
              "active" => true,
              "name" => "str_twitter",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 103,
            },
            {
              "active" => true,
              "name" => "str_website",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 104,
            },
            {
              "active" => true,
              "name" => "str_wikidata_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 105,
            },
            {
              "active" => true,
              "name" => "str_wikipedia_id",
              "req" => false,
              "type" => "`$STRING`",
              "index$" => 106,
            },
          ],
          "name" => "v1_search",
          "op" => {
            "list" => {
              "input" => "data",
              "name" => "list",
              "points" => [
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "Homework",
                        "kind" => "query",
                        "name" => "a",
                        "orig" => "a",
                        "reqd" => false,
                        "type" => "`$STRING`",
                      },
                      {
                        "active" => true,
                        "example" => "daft_punk",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/searchalbum.php",
                  "parts" => [
                    "searchalbum.php",
                  ],
                  "select" => {
                    "exist" => [
                      "a",
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 0,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "coldplay",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                      {
                        "active" => true,
                        "example" => "yellow",
                        "kind" => "query",
                        "name" => "t",
                        "orig" => "t",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/searchtrack.php",
                  "parts" => [
                    "searchtrack.php",
                  ],
                  "select" => {
                    "exist" => [
                      "s",
                      "t",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 1,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/discography-mb.php",
                  "parts" => [
                    "discography-mb.php",
                  ],
                  "select" => {
                    "exist" => [
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 2,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "coldplay",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/discography.php",
                  "parts" => [
                    "discography.php",
                  ],
                  "select" => {
                    "exist" => [
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 3,
                },
                {
                  "active" => true,
                  "args" => {
                    "query" => [
                      {
                        "active" => true,
                        "example" => "coldplay",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => true,
                        "type" => "`$STRING`",
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/search.php",
                  "parts" => [
                    "search.php",
                  ],
                  "select" => {
                    "exist" => [
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 4,
                },
              ],
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "v2_list" => {
          "fields" => [
            {
              "active" => true,
              "name" => "album",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 0,
            },
          ],
          "name" => "v2_list",
          "op" => {
            "load" => {
              "input" => "data",
              "name" => "load",
              "points" => [
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => 111239,
                        "kind" => "param",
                        "name" => "artist_id",
                        "orig" => "artist_id",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/list/discography/{artistId}",
                  "parts" => [
                    "list",
                    "discography",
                    "{artist_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "artistId" => "artist_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "artist_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 0,
                },
              ],
              "key$" => "load",
            },
          },
          "relations" => {
            "ancestors" => [
              [
                "discography",
              ],
            ],
          },
        },
        "v2_lookup" => {
          "fields" => [
            {
              "active" => true,
              "name" => "album",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 0,
            },
            {
              "active" => true,
              "name" => "artist",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 1,
            },
            {
              "active" => true,
              "name" => "track",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 2,
            },
          ],
          "name" => "v2_lookup",
          "op" => {
            "load" => {
              "input" => "data",
              "name" => "load",
              "points" => [
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => 2109615,
                        "kind" => "param",
                        "name" => "album_id",
                        "orig" => "album_id",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup/album/{albumId}",
                  "parts" => [
                    "lookup",
                    "album",
                    "{album_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "albumId" => "album_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "album_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 0,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => 111239,
                        "kind" => "param",
                        "name" => "artist_id",
                        "orig" => "artist_id",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup/artist/{artistId}",
                  "parts" => [
                    "lookup",
                    "artist",
                    "{artist_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "artistId" => "artist_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "artist_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 1,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => "1dc4c347-a1db-32aa-b14f-bc9cc507b843",
                        "kind" => "param",
                        "name" => "music_brainz_id",
                        "orig" => "music_brainz_id",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup/album_mb/{musicBrainzId}",
                  "parts" => [
                    "lookup",
                    "album_mb",
                    "{music_brainz_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "musicBrainzId" => "music_brainz_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "music_brainz_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 2,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => "cc197bad-dc9c-440d-a5b5-d52ba2e14234",
                        "kind" => "param",
                        "name" => "music_brainz_id",
                        "orig" => "music_brainz_id",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup/artist_mb/{musicBrainzId}",
                  "parts" => [
                    "lookup",
                    "artist_mb",
                    "{music_brainz_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "musicBrainzId" => "music_brainz_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "music_brainz_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 3,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => "50369905-68ca-48d2-912d-b37330ff7dc3",
                        "kind" => "param",
                        "name" => "music_brainz_id",
                        "orig" => "music_brainz_id",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup/track_mb/{musicBrainzId}",
                  "parts" => [
                    "lookup",
                    "track_mb",
                    "{music_brainz_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "musicBrainzId" => "music_brainz_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "music_brainz_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 4,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => 32724183,
                        "kind" => "param",
                        "name" => "track_id",
                        "orig" => "track_id",
                        "reqd" => true,
                        "type" => "`$INTEGER`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup/track/{trackId}",
                  "parts" => [
                    "lookup",
                    "track",
                    "{track_id}",
                  ],
                  "rename" => {
                    "param" => {
                      "trackId" => "track_id",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "track_id",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 5,
                },
              ],
              "key$" => "load",
            },
          },
          "relations" => {
            "ancestors" => [
              [
                "album",
              ],
              [
                "album_mb",
              ],
              [
                "artist",
              ],
              [
                "artist_mb",
              ],
              [
                "track",
              ],
              [
                "track_mb",
              ],
            ],
          },
        },
        "v2_search" => {
          "fields" => [
            {
              "active" => true,
              "name" => "album",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 0,
            },
            {
              "active" => true,
              "name" => "artist",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 1,
            },
            {
              "active" => true,
              "name" => "track",
              "req" => false,
              "type" => "`$ARRAY`",
              "index$" => 2,
            },
          ],
          "name" => "v2_search",
          "op" => {
            "load" => {
              "input" => "data",
              "name" => "load",
              "points" => [
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => "parachutes",
                        "kind" => "param",
                        "name" => "album_name",
                        "orig" => "album_name",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/search/album/{albumName}",
                  "parts" => [
                    "search",
                    "album",
                    "{album_name}",
                  ],
                  "rename" => {
                    "param" => {
                      "albumName" => "album_name",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "album_name",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 0,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => "coldplay",
                        "kind" => "param",
                        "name" => "artist_name",
                        "orig" => "artist_name",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/search/artist/{artistName}",
                  "parts" => [
                    "search",
                    "artist",
                    "{artist_name}",
                  ],
                  "rename" => {
                    "param" => {
                      "artistName" => "artist_name",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "artist_name",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 1,
                },
                {
                  "active" => true,
                  "args" => {
                    "params" => [
                      {
                        "active" => true,
                        "example" => "yellow",
                        "kind" => "param",
                        "name" => "track_name",
                        "orig" => "track_name",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "index$" => 0,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/search/track/{trackName}",
                  "parts" => [
                    "search",
                    "track",
                    "{track_name}",
                  ],
                  "rename" => {
                    "param" => {
                      "trackName" => "track_name",
                    },
                  },
                  "select" => {
                    "exist" => [
                      "track_name",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "index$" => 2,
                },
              ],
              "key$" => "load",
            },
          },
          "relations" => {
            "ancestors" => [
              [
                "album",
              ],
              [
                "artist",
              ],
              [
                "track",
              ],
            ],
          },
        },
      },
    }
  end


  def self.make_feature(name)
    require_relative 'features'
    FreeMusicApi2Features.make_feature(name)
  end
end
