// Typed models for the FreeMusicApi2 SDK.
//
// GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
// params (op.<name>.points[].args.params[]). Field/param types come from the
// canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
// @voxgig/apidef VALID_CANON). Do not edit by hand.

export interface V1List {
  idAlbum?: number
  idArtist?: number
  idIMVDB?: number
  idLyric?: number
  idTrack?: number
  intCD?: number
  intDuration?: number
  intLoved?: number
  intMusicVidComments?: number
  intMusicVidDislikes?: number
  intMusicVidFavorites?: number
  intMusicVidLikes?: number
  intMusicVidViews?: number
  intScore?: number
  intScoreVotes?: number
  intTotalListeners?: number
  intTotalPlays?: number
  intTrackNumber?: number
  loved?: any[]
  strAlbum?: string
  strArtist?: string
  strArtistAlternate?: string
  strDescriptionEN?: string
  strGenre?: string
  strLocked?: string
  strMood?: string
  strMusicBrainzAlbumID?: string
  strMusicBrainzArtistID?: string
  strMusicBrainzID?: string
  strMusicVid?: string
  strMusicVidCompany?: string
  strMusicVidDirector?: string
  strMusicVidScreen1?: string
  strMusicVidScreen2?: string
  strMusicVidScreen3?: string
  strStyle?: string
  strTheme?: string
  strTrack?: string
  strTrackLyrics?: string
  strTrackThumb?: string
  trending?: any[]
}

export interface V1ListListMatch {
  idAlbum?: number
  idArtist?: number
  idIMVDB?: number
  idLyric?: number
  idTrack?: number
  intCD?: number
  intDuration?: number
  intLoved?: number
  intMusicVidComments?: number
  intMusicVidDislikes?: number
  intMusicVidFavorites?: number
  intMusicVidLikes?: number
  intMusicVidViews?: number
  intScore?: number
  intScoreVotes?: number
  intTotalListeners?: number
  intTotalPlays?: number
  intTrackNumber?: number
  loved?: any[]
  strAlbum?: string
  strArtist?: string
  strArtistAlternate?: string
  strDescriptionEN?: string
  strGenre?: string
  strLocked?: string
  strMood?: string
  strMusicBrainzAlbumID?: string
  strMusicBrainzArtistID?: string
  strMusicBrainzID?: string
  strMusicVid?: string
  strMusicVidCompany?: string
  strMusicVidDirector?: string
  strMusicVidScreen1?: string
  strMusicVidScreen2?: string
  strMusicVidScreen3?: string
  strStyle?: string
  strTheme?: string
  strTrack?: string
  strTrackLyrics?: string
  strTrackThumb?: string
  trending?: any[]
}

export interface V1Lookup {
  idAlbum?: number
  idArtist?: number
  idIMVDB?: number
  idLabel?: number
  idLyric?: number
  idTrack?: number
  intBornYear?: number
  intCD?: number
  intCharted?: number
  intDiedYear?: number
  intDuration?: number
  intFormedYear?: number
  intLoved?: number
  intMembers?: number
  intMusicVidComments?: number
  intMusicVidDislikes?: number
  intMusicVidFavorites?: number
  intMusicVidLikes?: number
  intMusicVidViews?: number
  intSales?: number
  intScore?: number
  intScoreVotes?: number
  intTotalListeners?: number
  intTotalPlays?: number
  intTrackNumber?: number
  intYearReleased?: number
  strAlbum?: string
  strAlbum3DCase?: string
  strAlbum3DFace?: string
  strAlbum3DFlat?: string
  strAlbum3DThumb?: string
  strAlbumCDart?: string
  strAlbumSpine?: string
  strAlbumStripped?: string
  strAlbumThumb?: string
  strAlbumThumbBack?: string
  strAlbumThumbHQ?: string
  strAllMusicID?: string
  strAmazonID?: string
  strAppleMusic?: string
  strArtist?: string
  strArtistAlternate?: string
  strArtistBanner?: string
  strArtistClearart?: string
  strArtistCutout?: string
  strArtistFanart?: string
  strArtistFanart2?: string
  strArtistFanart3?: string
  strArtistFanart4?: string
  strArtistLogo?: string
  strArtistStripped?: string
  strArtistThumb?: string
  strArtistWideThumb?: string
  strBBCReviewID?: string
  strBiographyCN?: string
  strBiographyDE?: string
  strBiographyEN?: string
  strBiographyES?: string
  strBiographyFR?: string
  strBiographyHU?: string
  strBiographyIL?: string
  strBiographyIT?: string
  strBiographyJP?: string
  strBiographyNL?: string
  strBiographyNO?: string
  strBiographyPL?: string
  strBiographyPT?: string
  strBiographyRU?: string
  strBiographySE?: string
  strCountry?: string
  strCountryCode?: string
  strDescriptionEN?: string
  strDisbanded?: string
  strDiscogsID?: string
  strFacebook?: string
  strGender?: string
  strGeniusID?: string
  strGenre?: string
  strInstagram?: string
  strItunesID?: string
  strLabel?: string
  strLastFMChart?: string
  strLocation?: string
  strLocked?: string
  strLyricWikiID?: string
  strMood?: string
  strMusicBrainzAlbumID?: string
  strMusicBrainzArtistID?: string
  strMusicBrainzID?: string
  strMusicMozID?: string
  strMusicVid?: string
  strMusicVidCompany?: string
  strMusicVidDirector?: string
  strMusicVidScreen1?: string
  strMusicVidScreen2?: string
  strMusicVidScreen3?: string
  strRateYourMusicID?: string
  strReleaseFormat?: string
  strReview?: string
  strSoundCloud?: string
  strSpeed?: string
  strSpotify?: string
  strStyle?: string
  strTheme?: string
  strTrack?: string
  strTrackLyrics?: string
  strTrackThumb?: string
  strTwitter?: string
  strWebsite?: string
  strWikidataID?: string
  strWikipediaID?: string
  strYoutube?: string
}

export interface V1LookupListMatch {
  idAlbum?: number
  idArtist?: number
  idIMVDB?: number
  idLabel?: number
  idLyric?: number
  idTrack?: number
  intBornYear?: number
  intCD?: number
  intCharted?: number
  intDiedYear?: number
  intDuration?: number
  intFormedYear?: number
  intLoved?: number
  intMembers?: number
  intMusicVidComments?: number
  intMusicVidDislikes?: number
  intMusicVidFavorites?: number
  intMusicVidLikes?: number
  intMusicVidViews?: number
  intSales?: number
  intScore?: number
  intScoreVotes?: number
  intTotalListeners?: number
  intTotalPlays?: number
  intTrackNumber?: number
  intYearReleased?: number
  strAlbum?: string
  strAlbum3DCase?: string
  strAlbum3DFace?: string
  strAlbum3DFlat?: string
  strAlbum3DThumb?: string
  strAlbumCDart?: string
  strAlbumSpine?: string
  strAlbumStripped?: string
  strAlbumThumb?: string
  strAlbumThumbBack?: string
  strAlbumThumbHQ?: string
  strAllMusicID?: string
  strAmazonID?: string
  strAppleMusic?: string
  strArtist?: string
  strArtistAlternate?: string
  strArtistBanner?: string
  strArtistClearart?: string
  strArtistCutout?: string
  strArtistFanart?: string
  strArtistFanart2?: string
  strArtistFanart3?: string
  strArtistFanart4?: string
  strArtistLogo?: string
  strArtistStripped?: string
  strArtistThumb?: string
  strArtistWideThumb?: string
  strBBCReviewID?: string
  strBiographyCN?: string
  strBiographyDE?: string
  strBiographyEN?: string
  strBiographyES?: string
  strBiographyFR?: string
  strBiographyHU?: string
  strBiographyIL?: string
  strBiographyIT?: string
  strBiographyJP?: string
  strBiographyNL?: string
  strBiographyNO?: string
  strBiographyPL?: string
  strBiographyPT?: string
  strBiographyRU?: string
  strBiographySE?: string
  strCountry?: string
  strCountryCode?: string
  strDescriptionEN?: string
  strDisbanded?: string
  strDiscogsID?: string
  strFacebook?: string
  strGender?: string
  strGeniusID?: string
  strGenre?: string
  strInstagram?: string
  strItunesID?: string
  strLabel?: string
  strLastFMChart?: string
  strLocation?: string
  strLocked?: string
  strLyricWikiID?: string
  strMood?: string
  strMusicBrainzAlbumID?: string
  strMusicBrainzArtistID?: string
  strMusicBrainzID?: string
  strMusicMozID?: string
  strMusicVid?: string
  strMusicVidCompany?: string
  strMusicVidDirector?: string
  strMusicVidScreen1?: string
  strMusicVidScreen2?: string
  strMusicVidScreen3?: string
  strRateYourMusicID?: string
  strReleaseFormat?: string
  strReview?: string
  strSoundCloud?: string
  strSpeed?: string
  strSpotify?: string
  strStyle?: string
  strTheme?: string
  strTrack?: string
  strTrackLyrics?: string
  strTrackThumb?: string
  strTwitter?: string
  strWebsite?: string
  strWikidataID?: string
  strWikipediaID?: string
  strYoutube?: string
}

export interface V1Search {
  idAlbum?: number
  idArtist?: number
  idIMVDB?: number
  idLabel?: number
  idLyric?: number
  idTrack?: number
  intBornYear?: number
  intCD?: number
  intCharted?: number
  intDiedYear?: number
  intDuration?: number
  intFormedYear?: number
  intLoved?: number
  intMembers?: number
  intMusicVidComments?: number
  intMusicVidDislikes?: number
  intMusicVidFavorites?: number
  intMusicVidLikes?: number
  intMusicVidViews?: number
  intSales?: number
  intScore?: number
  intScoreVotes?: number
  intTotalListeners?: number
  intTotalPlays?: number
  intTrackNumber?: number
  intYearReleased?: number
  strAlbum?: string
  strAlbum3DCase?: string
  strAlbum3DFace?: string
  strAlbum3DFlat?: string
  strAlbum3DThumb?: string
  strAlbumCDart?: string
  strAlbumSpine?: string
  strAlbumStripped?: string
  strAlbumThumb?: string
  strAlbumThumbBack?: string
  strAlbumThumbHQ?: string
  strAllMusicID?: string
  strAmazonID?: string
  strArtist?: string
  strArtistAlternate?: string
  strArtistBanner?: string
  strArtistClearart?: string
  strArtistCutout?: string
  strArtistFanart?: string
  strArtistFanart2?: string
  strArtistFanart3?: string
  strArtistFanart4?: string
  strArtistLogo?: string
  strArtistStripped?: string
  strArtistThumb?: string
  strArtistWideThumb?: string
  strBBCReviewID?: string
  strBiographyCN?: string
  strBiographyDE?: string
  strBiographyEN?: string
  strBiographyES?: string
  strBiographyFR?: string
  strBiographyHU?: string
  strBiographyIL?: string
  strBiographyIT?: string
  strBiographyJP?: string
  strBiographyNL?: string
  strBiographyNO?: string
  strBiographyPL?: string
  strBiographyPT?: string
  strBiographyRU?: string
  strBiographySE?: string
  strCountry?: string
  strCountryCode?: string
  strDescriptionEN?: string
  strDisbanded?: string
  strDiscogsID?: string
  strFacebook?: string
  strGender?: string
  strGeniusID?: string
  strGenre?: string
  strItunesID?: string
  strLabel?: string
  strLastFMChart?: string
  strLocation?: string
  strLocked?: string
  strLyricWikiID?: string
  strMood?: string
  strMusicBrainzAlbumID?: string
  strMusicBrainzArtistID?: string
  strMusicBrainzID?: string
  strMusicMozID?: string
  strMusicVid?: string
  strMusicVidCompany?: string
  strMusicVidDirector?: string
  strMusicVidScreen1?: string
  strMusicVidScreen2?: string
  strMusicVidScreen3?: string
  strRateYourMusicID?: string
  strReleaseFormat?: string
  strReview?: string
  strSpeed?: string
  strStyle?: string
  strTheme?: string
  strTrack?: string
  strTrackLyrics?: string
  strTrackThumb?: string
  strTwitter?: string
  strWebsite?: string
  strWikidataID?: string
  strWikipediaID?: string
}

export interface V1SearchListMatch {
  idAlbum?: number
  idArtist?: number
  idIMVDB?: number
  idLabel?: number
  idLyric?: number
  idTrack?: number
  intBornYear?: number
  intCD?: number
  intCharted?: number
  intDiedYear?: number
  intDuration?: number
  intFormedYear?: number
  intLoved?: number
  intMembers?: number
  intMusicVidComments?: number
  intMusicVidDislikes?: number
  intMusicVidFavorites?: number
  intMusicVidLikes?: number
  intMusicVidViews?: number
  intSales?: number
  intScore?: number
  intScoreVotes?: number
  intTotalListeners?: number
  intTotalPlays?: number
  intTrackNumber?: number
  intYearReleased?: number
  strAlbum?: string
  strAlbum3DCase?: string
  strAlbum3DFace?: string
  strAlbum3DFlat?: string
  strAlbum3DThumb?: string
  strAlbumCDart?: string
  strAlbumSpine?: string
  strAlbumStripped?: string
  strAlbumThumb?: string
  strAlbumThumbBack?: string
  strAlbumThumbHQ?: string
  strAllMusicID?: string
  strAmazonID?: string
  strArtist?: string
  strArtistAlternate?: string
  strArtistBanner?: string
  strArtistClearart?: string
  strArtistCutout?: string
  strArtistFanart?: string
  strArtistFanart2?: string
  strArtistFanart3?: string
  strArtistFanart4?: string
  strArtistLogo?: string
  strArtistStripped?: string
  strArtistThumb?: string
  strArtistWideThumb?: string
  strBBCReviewID?: string
  strBiographyCN?: string
  strBiographyDE?: string
  strBiographyEN?: string
  strBiographyES?: string
  strBiographyFR?: string
  strBiographyHU?: string
  strBiographyIL?: string
  strBiographyIT?: string
  strBiographyJP?: string
  strBiographyNL?: string
  strBiographyNO?: string
  strBiographyPL?: string
  strBiographyPT?: string
  strBiographyRU?: string
  strBiographySE?: string
  strCountry?: string
  strCountryCode?: string
  strDescriptionEN?: string
  strDisbanded?: string
  strDiscogsID?: string
  strFacebook?: string
  strGender?: string
  strGeniusID?: string
  strGenre?: string
  strItunesID?: string
  strLabel?: string
  strLastFMChart?: string
  strLocation?: string
  strLocked?: string
  strLyricWikiID?: string
  strMood?: string
  strMusicBrainzAlbumID?: string
  strMusicBrainzArtistID?: string
  strMusicBrainzID?: string
  strMusicMozID?: string
  strMusicVid?: string
  strMusicVidCompany?: string
  strMusicVidDirector?: string
  strMusicVidScreen1?: string
  strMusicVidScreen2?: string
  strMusicVidScreen3?: string
  strRateYourMusicID?: string
  strReleaseFormat?: string
  strReview?: string
  strSpeed?: string
  strStyle?: string
  strTheme?: string
  strTrack?: string
  strTrackLyrics?: string
  strTrackThumb?: string
  strTwitter?: string
  strWebsite?: string
  strWikidataID?: string
  strWikipediaID?: string
}

export interface V2List {
  albums?: any[]
}

export interface V2ListLoadMatch {
  artist_id: number
}

export interface V2Lookup {
  albums?: any[]
  artists?: any[]
  tracks?: any[]
}

export interface V2LookupLoadMatch {
  album_id: number
}

export interface V2Search {
  albums?: any[]
  artists?: any[]
  tracks?: any[]
}

export interface V2SearchLoadMatch {
  album_name: string
}

